#!/bin/bash

read -p "Name of this project: " project
read -p "AWS Admin account email address: " email
read -p "Enter your AWS Access Key ID: " key
read -p "Enter your AWS Secret Access Key: "$'\n' -s secret
read -p "What's your preferred AWS region? (default: us-east-1): " region
read -p "What's the name of your Terraform Cloud organization?: " ORG_NAME
echo ""

for i in $(find . -name "[0-9][0-9]-*" -type d -maxdepth 1);
do
  for f in $(find $i -name "*.tf" -type f -maxdepth 1);
  do 
      fname=$(basename $f)
      cat $f >> $fname
  done
  terraform init
  AWS_ACCESS_KEY_ID=$key AWS_SECRET_ACCESS_KEY=$secret terraform apply -auto-approve
done

for f in $(find ./base -name "*.tf" -type f -maxdepth 1);
do 
    fname=$(basename $f)
    cat $f >> $fname
done

if [ ! -f "state.tf" ]; then
    cp state.tf.tmpl state.tf
    sed -i "" 's/#{org_name}/'$ORG_NAME'/' state.tf
fi

terraform init -migrate-state
terraform plan -var project_name=$project -var region=$region -var admin_email=$email